version: '3.9'
services:
  typescript_api_sqlite:
    build: .
    container_name: person-api-service-typescript-sqlite
    environment:
      - PERSON_REPO_BACKEND=sqlite
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db
    profiles: [sqlite]
  typescript_api_mongo:
    build: .
    container_name: person-api-service-typescript-mongo
    environment:
      - PERSON_REPO_BACKEND=mongo
      - MONGO_URI=mongodb://superuser:supersecret@mongo:27017/person_db?authSource=admin
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    profiles: [mongo]
  mongo:
    platform: linux/amd64
    image: mongo:8.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: superuser
      MONGO_INITDB_ROOT_PASSWORD: supersecret
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    profiles: [mongo]
volumes:
  mongo_data:
