---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-api-sqlite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-api-sqlite
  template:
    metadata:
      labels:
        app: dotnet-api-sqlite
    spec:
      containers:
        - name: dotnet-api-sqlite
          image: person_api_service_dotnet_api_sqlite:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: PERSON_REPO_BACKEND
              value: "sqlite"
          volumeMounts:
            - name: db-volume
              mountPath: /app/db
      volumes:
        - name: db-volume
          hostPath:
            path: /tmp/dotnet_person_api_db
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-api-sqlite
spec:
  type: NodePort
  selector:
    app: dotnet-api-sqlite
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-api-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-api-mongo
  template:
    metadata:
      labels:
        app: dotnet-api-mongo
    spec:
      containers:
        - name: dotnet-api-mongo
          image: person_api_service_dotnet_api_mongo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: PERSON_REPO_BACKEND
              value: "mongo"
            - name: MONGO_URI
              value: "mongodb://superuser:supersecret@mongo:27017/person_db?authSource=admin"
      # No volume needed for mongo repo
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-api-mongo
spec:
  type: NodePort
  selector:
    app: dotnet-api-mongo
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:8.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: superuser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: supersecret
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      # No nodePort for mongo by default
